apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
  labels:
    app: argo-workflows
    project: tas
data:
  default-v1: |
    archiveLogs: true
    s3:
      bucket: argo-artifacts
      endpoint: minio-shared.tas-shared.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: minio-credentials
        key: accesskey
      secretKeySecret:
        name: minio-credentials
        key: secretkey
