apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: argo
  labels:
    app: argo-workflows
    project: tas
type: Opaque
stringData:
  accesskey: "minioadmin"
  secretkey: "minioadmin123"
