apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: argo-events
  labels:
    app: argo-events
    project: tas
type: Opaque
stringData:
  accesskey: "minioadmin"
  secretkey: "minioadmin123"
