---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-shared-sa
  namespace: tas-shared

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-shared-logs-reader
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - nodes
  - nodes/proxy
  - services
  - endpoints
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-shared-logs-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-shared-logs-reader
subjects:
- kind: ServiceAccount
  name: alloy-shared-sa
  namespace: tas-shared
