apiVersion: v1
kind: Secret
metadata:
  name: godaddy-api-key
  namespace: cert-manager
type: Opaque
stringData:
  # Get these from https://developer.godaddy.com/keys
  # Use "Production" environment keys
  api-key: "YOUR_GODADDY_API_KEY"
  api-secret: "YOUR_GODADDY_API_SECRET"
