apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-dev
  namespace: tas-dev
  labels:
    app: loki-dev
    component: logging
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-dev
  template:
    metadata:
      labels:
        app: loki-dev
        component: logging
        environment: development
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.4.0
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        args:
        - -config.file=/etc/loki/loki-config.yml
        - -target=all
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-storage
          mountPath: /loki
        env:
        - name: LOKI_MODE
          value: "development"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: loki-config
        configMap:
          name: loki-dev-config
      - name: loki-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki-dev
  namespace: tas-dev
  labels:
    app: loki-dev
    component: logging
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http
  - port: 9096
    targetPort: 9096
    protocol: TCP
    name: grpc
  selector:
    app: loki-dev

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-dev-config
  namespace: tas-dev
  labels:
    app: loki-dev
    component: logging
data:
  loki-config.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 20MB
      max_concurrent_tail_requests: 20
      max_streams_per_user: 10000

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 5m
      retention_enabled: false

    analytics:
      reporting_enabled: false

    frontend:
      max_outstanding_per_tenant: 512
      compress_responses: true

    querier:
      max_concurrent: 20